"""
Company Balance Sheet Statement Schema
Definition of the json-schema for the balance sheet statement response.
"""

COMPANY_BALANCE_SHEET_STATEMENT_SCHEMA = {
    "type": "array",
    "items": {"type": "object",
              "properties":
                  {
                      "date": {"type": "string"},
                      "symbol": {"type": "string"},
                      "reportedCurrency": {"type": "string"},
                      "cik": {"type": "string"},
                      "fillingDate": {"type": "string"},
                      "acceptedDate": {"type": "string"},
                      "calendarYear": {"type": "string"},
                      "period": {"type": "string"},
                      "cashAndCashEquivalents": {"type": "number"},
                      "shortTermInvestments": {"type": "number"},
                      "cashAndShortTermInvestments": {"type": "number"},
                      "netReceivables": {"type": "number"},
                      "inventory": {"type": "number"},
                      "otherCurrentAssets": {"type": "number"},
                      "totalCurrentAssets": {"type": "number"},
                      "propertyPlantEquipmentNet": {"type": "number"},
                      "goodwill": {"type": "number"},
                      "intangibleAssets": {"type": "number"},
                      "goodwillAndIntangibleAssets": {"type": "number"},
                      "longTermInvestments": {"type": "number"},
                      "taxAssets": {"type": "number"},
                      "otherNonCurrentAssets": {"type": "number"},
                      "totalNonCurrentAssets": {"type": "number"},
                      "otherAssets": {"type": "number"},
                      "totalAssets": {"type": "number"},
                      "accountPayables": {"type": "number"},
                      "shortTermDebt": {"type": "number"},
                      "taxPayables": {"type": "number"},
                      "deferredRevenue": {"type": "number"},
                      "otherCurrentLiabilities": {"type": "number"},
                      "totalCurrentLiabilities": {"type": "number"},
                      "longTermDebt": {"type": "number"},
                      "deferredRevenueNonCurrent": {"type": "number"},
                      "deferredTaxLiabilitiesNonCurrent": {"type": "number"},
                      "otherNonCurrentLiabilities": {"type": "number"},
                      "totalNonCurrentLiabilities": {"type": "number"},
                      "otherLiabilities": {"type": "number"},
                      "capitalLeaseObligations": {"type": "number"},
                      "totalLiabilities": {"type": "number"},
                      "preferredStock": {"type": "number"},
                      "commonStock": {"type": "number"},
                      "retainedEarnings": {"type": "number"},
                      "accumulatedOtherComprehensiveIncomeLoss": {"type": "number"},
                      "othertotalStockholdersEquity": {"type": "number"},
                      "totalStockholdersEquity": {"type": "number"},
                      "totalLiabilitiesAndStockholdersEquity": {"type": "number"},
                      "minorityInterest": {"type": "number"},
                      "totalEquity": {"type": "number"},
                      "totalLiabilitiesAndTotalEquity": {"type": "number"},
                      "totalInvestments": {"type": "number"},
                      "totalDebt": {"type": "number"},
                      "netDebt": {"type": "number"},
                      "link": {"type": "string"},
                      "finalLink": {"type": "string"}
                  },
              "additionalProperties": False,
              "minProperties": 54
              }
}
