COMPANY_KEY_METRICS_SCHEMA = {
    "type": "array",
    "items": {"type": "object",
              "properties":
                  {
                      "date": {"type": "string"},
                      "symbol": {"type": "string"},
                      "period": {"type": "string"},
                      "revenuePerShare": {"type": "number"},
                      "netIncomePerShare": {"type": "number"},
                      "operatingCashFlowPerShare": {"type": "number"},
                      "freeCashFlowPerShare": {"type": "number"},
                      "cashPerShare": {"type": "number"},
                      "bookValuePerShare": {"type": "number"},
                      "tangibleBookValuePerShare": {"type": "number"},
                      "shareholdersEquityPerShare": {"type": "number"},
                      "interestDebtPerShare": {"type": "number"},
                      "marketCap": {"type": "number"},
                      "enterpriseValue": {"type": "number"},
                      "peRatio": {"type": "number"},
                      "priceToSalesRatio": {"type": "number"},
                      "pocfratio": {"type": "number"},
                      "pfcfRatio": {"type": "number"},
                      "pbRatio": {"type": "number"},
                      "ptbRatio": {"type": "number"},
                      "evToSales": {"type": "number"},
                      "enterpriseValueOverEBITDA": {"type": "number"},
                      "evToOperatingCashFlow": {"type": "number"},
                      "evToFreeCashFlow": {"type": "number"},
                      "earningsYield": {"type": "number"},
                      "freeCashFlowYield": {"type": "number"},
                      "debtToEquity": {"type": "number"},
                      "debtToAssets": {"type": "number"},
                      "netDebtToEBITDA": {"type": "number"},
                      "currentRatio": {"type": "number"},
                      "interestCoverage": {"type": "number"},
                      "incomeQuality": {"type": "number"},
                      "dividendYield": {"type": "number"},
                      "payoutRatio": {"type": "number"},
                      "salesGeneralAndAdministrativeToRevenue": {"type": "number"},
                      "researchAndDdevelopementToRevenue": {"type": "number"},
                      "intangiblesToTotalAssets": {"type": "number"},
                      "capexToOperatingCashFlow": {"type": "number"},
                      "capexToRevenue": {"type": "number"},
                      "capexToDepreciation": {"type": "number"},
                      "stockBasedCompensationToRevenue": {"type": "number"},
                      "grahamNumber": {"type": "number"},
                      "roic": {"type": "number"},
                      "returnOnTangibleAssets": {"type": "number"},
                      "grahamNetNet": {"type": "number"},
                      "workingCapital": {"type": "number"},
                      "tangibleAssetValue": {"type": ["number", "null"]},
                      "netCurrentAssetValue": {"type": "number"},
                      "investedCapital": {"type": "number"},
                      "averageReceivables": {"type": "number"},
                      "averagePayables": {"type": "number"},
                      "averageInventory": {"type": "number"},
                      "daysSalesOutstanding": {"type": "number"},
                      "daysPayablesOutstanding": {"type": "number"},
                      "daysOfInventoryOnHand": {"type": "number"},
                      "receivablesTurnover": {"type": "number"},
                      "payablesTurnover": {"type": "number"},
                      "inventoryTurnover": {"type": "number"},
                      "roe": {"type": "number"},
                      "capexPerShare": {"type": "number"}
                  },
              "additionalProperties": False,
              "minProperties": 60
              }
}
