COMPANY_FINANCIAL_RATIOS_SCHEMA = {
        "type": "array",
        "items": {"type": "object",
                  "properties":
                      {
                          "date": {"type": "string"},
                          "symbol": {"type": "string"},
                          "period": {"type": "string"},
                          "currentRatio": {"type": "number"},
                          "quickRatio": {"type": "number"},
                          "cashRatio": {"type": "number"},
                          "daysOfSalesOutstanding": {"type": "number"},
                          "daysOfInventoryOutstanding": {"type": "number"},
                          "operatingCycle": {"type": "number"},
                          "daysOfPayablesOutstanding": {"type": "number"},
                          "cashConversionCycle": {"type": "number"},
                          "grossProfitMargin": {"type": "number"},
                          "operatingProfitMargin": {"type": "number"},
                          "pretaxProfitMargin": {"type": "number"},
                          "netProfitMargin": {"type": "number"},
                          "effectiveTaxRate": {"type": "number"},
                          "returnOnAssets": {"type": "number"},
                          "returnOnEquity": {"type": "number"},
                          "returnOnCapitalEmployed": {"type": "number"},
                          "netIncomePerEBT": {"type": "number"},
                          "ebtPerEbit": {"type": "number"},
                          "ebitPerRevenue": {"type": "number"},
                          "debtRatio": {"type": "number"},
                          "debtEquityRatio": {"type": "number"},
                          "longTermDebtToCapitalization": {"type": "number"},
                          "totalDebtToCapitalization": {"type": "number"},
                          "interestCoverage": {"type": "number"},
                          "cashFlowToDebtRatio": {"type": "number"},
                          "companyEquityMultiplier": {"type": "number"},
                          "receivablesTurnover": {"type": "number"},
                          "payablesTurnover": {"type": "number"},
                          "inventoryTurnover": {"type": "number"},
                          "fixedAssetTurnover": {"type": "number"},
                          "assetTurnover": {"type": "number"},
                          "operatingCashFlowPerShare": {"type": "number"},
                          "freeCashFlowPerShare": {"type": "number"},
                          "cashPerShare": {"type": "number"},
                          "payoutRatio": {"type": "number"},
                          "operatingCashFlowSalesRatio": {"type": "number"},
                          "freeCashFlowOperatingCashFlowRatio": {"type": "number"},
                          "cashFlowCoverageRatios": {"type": "number"},
                          "shortTermCoverageRatios": {"type": "number"},
                          "capitalExpenditureCoverageRatio": {"type": "number"},
                          "dividendPaidAndCapexCoverageRatio": {"type": "number"},
                          "dividendPayoutRatio": {"type": "number"},
                          "priceBookValueRatio": {"type": "number"},
                          "priceToBookRatio": {"type": "number"},
                          "priceToSalesRatio": {"type": "number"},
                          "priceEarningsRatio": {"type": "number"},
                          "priceToFreeCashFlowsRatio": {"type": "number"},
                          "priceToOperatingCashFlowsRatio": {"type": "number"},
                          "priceCashFlowRatio": {"type": "number"},
                          "priceEarningsToGrowthRatio": {"type": "number"},
                          "priceSalesRatio": {"type": "number"},
                          "dividendYield": {"type": "number"},
                          "enterpriseValueMultiple": {"type": "number"},
                          "priceFairValue": {"type": "number"}
                      },
                  "additionalProperties": False,
                  "minProperties": 57
                  }
    }
