name: CI

on: [ pull_request ]

jobs:
  prepare_environment:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7

      - name: Install Dependencies
        run: make all-dependencies

      - name: Debug
        run: | 
          ls
          uname -a

      - name: Run Tests
        run: make tests
