name: CI

on: [ pull_request ]

jobs:
  continous_integration:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7

      - name: Virtual Environment
        run: make venv

      - name: Where I am
        run: |
          ls -lha

      - name: Install Dependencies
        run: make all-dependencies

      - name: Run Tests
        run: make tests
